<?php

// Load some data

require_once(dirname(dirname(__FILE__)) . '/queue/queue.php');


$urls=array(
'https://www.researchgate.net/publication/320321240_Phylogenetic_relationships_of_millipedes_in_the_subclass_Penicillata_Diplopoda_with_a_key_to_the_genera',
'https://www.researchgate.net/profile/Megan_Short3',
'https://www.researchgate.net/profile/Charles_Haddad',
'https://www.researchgate.net/profile/Yong_Min_Pui',

// Edinburgh
'https://www.researchgate.net/profile/Alan_Elliott4',
'https://www.researchgate.net/profile/Alan_Forrest',
'https://www.researchgate.net/profile/Alan_Forrest3',
'https://www.researchgate.net/profile/Aleix_Arnau_Soler',
'https://www.researchgate.net/profile/Alexandra_Wortley',
'https://www.researchgate.net/profile/Aline_Finger',
'https://www.researchgate.net/profile/Andrew_Kenny8',
'https://www.researchgate.net/profile/Anthony_Miller2',
'https://www.researchgate.net/profile/Antje_Ahrends',
'https://www.researchgate.net/profile/Axel_Poulsen',
'https://www.researchgate.net/profile/Barbara_Mackinder',
'https://www.researchgate.net/profile/Bhaskar_Adhikari',
'https://www.researchgate.net/profile/Brian_Coppins',
'https://www.researchgate.net/profile/Camila_Quinteros_Penafiel',
'https://www.researchgate.net/profile/Christine_Thompson4',
'https://www.researchgate.net/profile/Christopher_Walker5',
'https://www.researchgate.net/profile/Colin_Pendry',
'https://www.researchgate.net/profile/D_Knott',
'https://www.researchgate.net/profile/David_Long47',
'https://www.researchgate.net/profile/David_Mann6',
'https://www.researchgate.net/profile/David_Mitchell23',
'https://www.researchgate.net/profile/David_Mitchell51',
'https://www.researchgate.net/profile/David_Rae2',
'https://www.researchgate.net/profile/Deborah_Kohn',
'https://www.researchgate.net/profile/Deborah_Kohn3',
'https://www.researchgate.net/profile/Diego_Sanchez-Ganfornina',
'https://www.researchgate.net/profile/Edeline_Gagnon',
'https://www.researchgate.net/profile/Eden_House2',
'https://www.researchgate.net/profile/Elspeth_Haston',
'https://www.researchgate.net/profile/Flavia_Pezzini',
'https://www.researchgate.net/profile/Gail_Stott',
'https://www.researchgate.net/profile/Hannah_Wilson23',
'https://www.researchgate.net/profile/Hans_Sluiman',
'https://www.researchgate.net/profile/Ian_Hedge',
'https://www.researchgate.net/profile/Javier_Luna3',
'https://www.researchgate.net/profile/Jen_Farrar2',
'https://www.researchgate.net/profile/Joanne_Taylor18',
'https://www.researchgate.net/profile/John_Howieson4',
'https://www.researchgate.net/profile/John_Mcneill5',
'https://www.researchgate.net/profile/Julieth_Serrano2',
'https://www.researchgate.net/profile/Kanae_Nishii',
'https://www.researchgate.net/profile/Kate_Miller31',
'https://www.researchgate.net/profile/Katherine_Hayden',
'https://www.researchgate.net/profile/Laura_Forrest3',
'https://www.researchgate.net/profile/Laura_Keddie',
'https://www.researchgate.net/profile/Leonie_Alexander',
'https://www.researchgate.net/profile/Louis_Ronse_De_Craene',
'https://www.researchgate.net/profile/Louise_Olley2',
'https://www.researchgate.net/profile/M_Hughes2',
'https://www.researchgate.net/profile/Maca_Gomez-Gutierrez',
'https://www.researchgate.net/profile/Maggie_Mitchell',
'https://www.researchgate.net/profile/Marine_Pouget',
'https://www.researchgate.net/profile/Mark_Newman6',
'https://www.researchgate.net/profile/Markus_Ruhsam',
'https://www.researchgate.net/profile/Martin_Gardner',
'https://www.researchgate.net/profile/Martin_Pullan',
'https://www.researchgate.net/profile/Mary_Gibby',
'https://www.researchgate.net/profile/Mayra_Briceno2',
'https://www.researchgate.net/profile/Melanie_Bayo',
'https://www.researchgate.net/profile/Michael_Moeller6',
'https://www.researchgate.net/profile/Michelle_Hart2',
'https://www.researchgate.net/profile/Natalia_Contreras-Ortiz',
'https://www.researchgate.net/profile/Neil_Bell',
'https://www.researchgate.net/profile/Nicky_Sharp2',
'https://www.researchgate.net/profile/Paulina_Hechenleitner_V',
'https://www.researchgate.net/profile/Peter_Moonlight',
'https://www.researchgate.net/profile/Peter_Wilkie',
'https://www.researchgate.net/profile/Philip_Thomas2',
'https://www.researchgate.net/profile/R_Yahr',
'https://www.researchgate.net/profile/Rebecca_Hilgenhof',
'https://www.researchgate.net/profile/Robert_Cubey',
'https://www.researchgate.net/profile/Robyn_Drinkwater',
'https://www.researchgate.net/profile/Roger_Hyam',
'https://www.researchgate.net/profile/Ruth_Mcgregor',
'https://www.researchgate.net/profile/Sabina_Knees',
'https://www.researchgate.net/profile/Sadie_Barber',
'https://www.researchgate.net/profile/Sally_Eaton3',
'https://www.researchgate.net/profile/Sally_King4',
'https://www.researchgate.net/profile/Sarah_Roberts15',
'https://www.researchgate.net/profile/Sophie_Neale',
'https://www.researchgate.net/profile/Sophie_Williams4',
'https://www.researchgate.net/profile/Stephan_Helfer',
'https://www.researchgate.net/profile/Stephen_Mifsud',
'https://www.researchgate.net/profile/Suzanne_Cubey',
'https://www.researchgate.net/profile/Thibauld_Michel',
'https://www.researchgate.net/profile/Tiina_Sarkinen',
'https://www.researchgate.net/profile/Tony_Conlon',
'https://www.researchgate.net/profile/Wu_Huang5',
'https://www.researchgate.net/profile/Zin_Hter',

);

$urls = array(
//'https://www.researchgate.net/profile/Rudy_Jocque',
//'https://www.researchgate.net/scientific-contributions/2052836011_Wanda_Wesolowska',
'https://www.researchgate.net/profile/Alexander_Haas7',
);

$urls=array(
'https://www.researchgate.net/profile/Robert_Stone21',
'https://www.researchgate.net/profile/Imercia_Mona',
'https://www.researchgate.net/profile/Syd_Ramdhani',
'https://www.researchgate.net/profile/Jan_Frits_Veldkamp',


'https://www.researchgate.net/profile/Andrew_Rozefelds',
'https://www.researchgate.net/profile/Barbara_Baehr',
'https://www.researchgate.net/profile/Brit_Asmussen',
'https://www.researchgate.net/profile/Carole_Burrow2',
'https://www.researchgate.net/profile/Chris_Burwell2',
'https://www.researchgate.net/profile/Christine_Lambkin',
'https://www.researchgate.net/profile/Claudia_Arango',
'https://www.researchgate.net/profile/Debra_Lewis3',
'https://www.researchgate.net/profile/Espen_Knutsen',
'https://www.researchgate.net/profile/Geoff_Monteith',
'https://www.researchgate.net/profile/Geoff_Thompson4',
'https://www.researchgate.net/profile/Greg_Czechura',
'https://www.researchgate.net/profile/Greg_Daniels3',
'https://www.researchgate.net/profile/Imelda_Miller',
'https://www.researchgate.net/profile/Jeff_Johnson8',
'https://www.researchgate.net/profile/Jeremy_Wilson8',
'https://www.researchgate.net/profile/Jessica_Worthington_Wilmer',
'https://www.researchgate.net/profile/John_Hooper',
'https://www.researchgate.net/profile/John_Stanisic',
'https://www.researchgate.net/profile/Jonathan_Cramb',
'https://www.researchgate.net/profile/Judith_Hickson2',
'https://www.researchgate.net/profile/Kathryn_Hall',
'https://www.researchgate.net/profile/Keith_Mcdonald2',
'https://www.researchgate.net/profile/Kerry_Cody',
'https://www.researchgate.net/profile/Kevin_Lambkin',
'https://www.researchgate.net/profile/Lindsay_Popple',
'https://www.researchgate.net/profile/Malcolm_Dunning2',
'https://www.researchgate.net/profile/Mary_Dettmann',
'https://www.researchgate.net/profile/Merrick_Ekins',
'https://www.researchgate.net/profile/Michael_Rix2',
'https://www.researchgate.net/profile/Nick_Hadnutt',
'https://www.researchgate.net/profile/Niel_Bruce',
'https://www.researchgate.net/profile/Noel_Starick',
'https://www.researchgate.net/profile/Owen_Seeman',
'https://www.researchgate.net/profile/Paul_Muir2',
'https://www.researchgate.net/profile/Peter_Allsopp2',
'https://www.researchgate.net/profile/Peter_Davie',
'https://www.researchgate.net/profile/Rob_Shiels',
'https://www.researchgate.net/profile/Robert_Adlard',
'https://www.researchgate.net/profile/Robert_Raven',
'https://www.researchgate.net/profile/Robert_Whyte6',
'https://www.researchgate.net/profile/Rochelle_Lawrence2',
'https://www.researchgate.net/profile/Scott_Hocknull',
'https://www.researchgate.net/profile/Susan_Turner4',
'https://www.researchgate.net/profile/Susan_Wright8',


);

$urls = array(
'https://www.researchgate.net/profile/Arnaud_Henrard',
'https://www.researchgate.net/profile/Jan_Bosselaers',
'https://www.researchgate.net/profile/Szuts_Tamas',
'https://www.researchgate.net/profile/Norman_Platnick',
'https://www.researchgate.net/profile/Wayne_Maddison',
'https://www.researchgate.net/scientific-contributions/13451639_Nikolaj_Scharff',
'https://www.researchgate.net/profile/Jonathan_Coddington',
'https://www.researchgate.net/profile/Dimitar_Dimitrov8',
'https://www.researchgate.net/profile/Natalia_Chousou-Polydouri',
'https://www.researchgate.net/profile/David_Maddison3',
'https://www.researchgate.net/profile/Charles_Griswold',
'https://www.researchgate.net/profile/Jeremy_Miller2',
'https://www.researchgate.net/profile/Gonzalo_Giribet',
);

$urls=array(
'https://www.researchgate.net/profile/Hong_Truong_Luu',
'https://www.researchgate.net/profile/Dang_Tran_Huu',
'https://www.researchgate.net/profile/Jana_Leong-Skornickova',
'https://www.researchgate.net/profile/Mark_Newman6',
'https://www.researchgate.net/profile/Quoc_Nguyen45',


'https://www.researchgate.net/profile/Rajib_Gogoi3',

'https://www.researchgate.net/profile/Gopal_Krishna25',
'https://www.researchgate.net/profile/Karthigeyan_Kaliyamurthy',
'https://www.researchgate.net/profile/Tapas_Chakrabarty',
'https://www.researchgate.net/profile/P_Lakshminarasimhan',
'https://www.researchgate.net/profile/Shalini_Selvaraj3',
'https://www.researchgate.net/profile/Jetti_Swamy2',
'https://www.researchgate.net/profile/Ladan_Rasingam',

'https://www.researchgate.net/profile/Michal_Sochor',
'https://www.researchgate.net/profile/Martin_Dancak',
'https://www.researchgate.net/profile/Zuzana_Sochorova',
'https://www.researchgate.net/profile/Michal_Hrones',
);

$urls=array(

'https://www.researchgate.net/profile/Aaron_Davis3',
'https://www.researchgate.net/profile/Adrian_Loo2',
'https://www.researchgate.net/profile/Alan_Paton2',
'https://www.researchgate.net/profile/Alex_Monro',
'https://www.researchgate.net/profile/Alex_Roberts',
'https://www.researchgate.net/profile/Alexander_Papadopulos',
'https://www.researchgate.net/profile/Alexandre_Zuntini',
'https://www.researchgate.net/profile/Alice_Di_Sacco',
'https://www.researchgate.net/profile/Alison_Foster10',
'https://www.researchgate.net/profile/Alison_Moore',
'https://www.researchgate.net/profile/Alison_Scott-Brown',
'https://www.researchgate.net/profile/Aljos_Farjon',
'https://www.researchgate.net/profile/Amy_Barker3',
'https://www.researchgate.net/profile/Andre_Schuiteman',
'https://www.researchgate.net/profile/Andrew_Budden',
'https://www.researchgate.net/profile/Andrew_Helmstetter',
'https://www.researchgate.net/profile/Andrew_Webster8',
'https://www.researchgate.net/profile/Anna_Haigh',
'https://www.researchgate.net/profile/Anna_Nebot',
'https://www.researchgate.net/profile/Anna_Ralaiveloarisoa2',
'https://www.researchgate.net/profile/Anna_Trias_Blasi',
'https://www.researchgate.net/profile/Anne_Visscher',
'https://www.researchgate.net/profile/Anthony_Maldonado-Castro',
'https://www.researchgate.net/profile/Antony_Ainsworth',
'https://www.researchgate.net/profile/Aurelie_Grall',
'https://www.researchgate.net/profile/Barnaby_Walker2',
'https://www.researchgate.net/profile/Ben_Dickinson',
'https://www.researchgate.net/profile/Benedict_Pollard',
'https://www.researchgate.net/profile/Bente_Klitgaard',
'https://www.researchgate.net/profile/Bingyu_Li17',
'https://www.researchgate.net/profile/Brian_Douglas2',
'https://www.researchgate.net/profile/Brian_Schrire',
'https://www.researchgate.net/profile/C_Wilmot-Dear',
'https://www.researchgate.net/profile/Carolina_Lagos3',
'https://www.researchgate.net/profile/Carolina_Pavicic',
'https://www.researchgate.net/profile/Carolina_Tovar_Ingar',
'https://www.researchgate.net/profile/Catia_Canteiro',
'https://www.researchgate.net/profile/Charlotte_Couch',
'https://www.researchgate.net/profile/Charlotte_Seal',
'https://www.researchgate.net/profile/Chris_Cockel',
'https://www.researchgate.net/profile/Chrissie_Prychid',
'https://www.researchgate.net/profile/Christine_Barker',
'https://www.researchgate.net/profile/Christine_Leon',
'https://www.researchgate.net/profile/Clara_Saez',
'https://www.researchgate.net/profile/Clare_Drinkell',
'https://www.researchgate.net/profile/Clare_Trivedi',
'https://www.researchgate.net/profile/Colin_Clubbe',
'https://www.researchgate.net/profile/Cossu_Ta',
'https://www.researchgate.net/profile/Cynthia_Sothers',
'https://www.researchgate.net/profile/Daniel_Ballesteros2',
'https://www.researchgate.net/profile/Daniel_Cahen',
'https://www.researchgate.net/profile/Dario_Prada',
'https://www.researchgate.net/profile/David_Baines5',
'https://www.researchgate.net/profile/David_Cooke7',
'https://www.researchgate.net/profile/David_Goyder',
'https://www.researchgate.net/profile/David_Hawksworth',
'https://www.researchgate.net/profile/David_Rabehevitra2',
'https://www.researchgate.net/profile/David_Simpson5',
'https://www.researchgate.net/profile/Dion_Devey',
'https://www.researchgate.net/profile/Don_Kirkup',
'https://www.researchgate.net/profile/Edward_Jones17',
'https://www.researchgate.net/profile/Efisio_Mattana',
'https://www.researchgate.net/profile/Eimear_Nic_Lughadha',
'https://www.researchgate.net/profile/Elaine_Porter2',
'https://www.researchgate.net/profile/Elena_Arrigoni2',
'https://www.researchgate.net/profile/Elena_Castillo_Lorenzo',
'https://www.researchgate.net/profile/Elinor_Breman',
'https://www.researchgate.net/profile/Ellen_Baker8',
'https://www.researchgate.net/profile/Ellie_Merrett_Wade',
'https://www.researchgate.net/profile/Emma_Williams42',
'https://www.researchgate.net/profile/Ester_Gaya',
'https://www.researchgate.net/profile/Esther_Grosskopf',
'https://www.researchgate.net/profile/Felix_Forest',
'https://www.researchgate.net/profile/Femi_Sokoya3',
'https://www.researchgate.net/profile/Frances_Cook',
'https://www.researchgate.net/profile/Gemma_Bramley',
'https://www.researchgate.net/profile/Geoffrey_Hawtin',
'https://www.researchgate.net/profile/Geoffrey_Kibby',
'https://www.researchgate.net/profile/Geoffrey_Kibby2',
'https://www.researchgate.net/profile/Geoffrey_Kite',
'https://www.researchgate.net/profile/George_Gosline',
'https://www.researchgate.net/profile/Gerhard_Prenner',
'https://www.researchgate.net/profile/Gill_Challen',
'https://www.researchgate.net/profile/Grace_Brewer',
'https://www.researchgate.net/profile/GT_Prance',
'https://www.researchgate.net/profile/Guillermo_Federico_Padilla-Gonzalez',
'https://www.researchgate.net/profile/Hannah_Banks',
'https://www.researchgate.net/profile/Harry_Baldwin2',
'https://www.researchgate.net/profile/Heather_Angel',
'https://www.researchgate.net/profile/Heather_Lindon',
'https://www.researchgate.net/profile/Helen_Chadburn',
'https://www.researchgate.net/profile/Helen_Fortune_Hopkins',
'https://www.researchgate.net/profile/Helen_Hartley3',
'https://www.researchgate.net/profile/Helene_Ralimanana',
'https://www.researchgate.net/profile/Henintsoa_Razanajatovo',
'https://www.researchgate.net/profile/Hugh_Pritchard',
'https://www.researchgate.net/profile/Iain_Darbyshire',
'https://www.researchgate.net/profile/Iain_Farrell',
'https://www.researchgate.net/profile/Ian_Willey',
'https://www.researchgate.net/profile/Ilia_Leitch',
'https://www.researchgate.net/profile/Irina_Belyaeva',
'https://www.researchgate.net/profile/Isabel_Larridon',
'https://www.researchgate.net/profile/J_Clennett',
'https://www.researchgate.net/profile/Jack_Plummer',
'https://www.researchgate.net/profile/James_Borrell',
'https://www.researchgate.net/profile/James_Clarkson3',
'https://www.researchgate.net/profile/Jan_Hackel2',
'https://www.researchgate.net/profile/Jane_Browning',
'https://www.researchgate.net/profile/Jasmine_Salvati',
'https://www.researchgate.net/profile/Jeffrey_Joseph2',
'https://www.researchgate.net/profile/Jemma_Taylor2',
'https://www.researchgate.net/profile/Jennifer_Peach3',
'https://www.researchgate.net/profile/Jenny_Williams10',
'https://www.researchgate.net/profile/Jill_Kowal3',
'https://www.researchgate.net/profile/Jill_Turner10',
'https://www.researchgate.net/profile/Jj_Wood',
'https://www.researchgate.net/profile/Jo_Osborne2',
'https://www.researchgate.net/profile/John_Dickie',
'https://www.researchgate.net/profile/John_Dransfield',
'https://www.researchgate.net/profile/Jon_Shore',
'https://www.researchgate.net/profile/Jonas_Mueller4',
'https://www.researchgate.net/profile/Jonathan_Kendon',
'https://www.researchgate.net/profile/Josiah_Seaman',
'https://www.researchgate.net/profile/Juan_Viruel',
'https://www.researchgate.net/profile/Julia_Carretero2',
'https://www.researchgate.net/profile/Justin_Moat',
'https://www.researchgate.net/profile/Kare_Liimatainen',
'https://www.researchgate.net/profile/Kate_Hardwick',
'https://www.researchgate.net/profile/Katharine_Cook',
'https://www.researchgate.net/profile/Kay_Pennick',
'https://www.researchgate.net/profile/Kazutomo_Yokoya',
'https://www.researchgate.net/profile/Keith_Jones3',
'https://www.researchgate.net/profile/Kenwin_Liu',
'https://www.researchgate.net/profile/Kim_Walker4',
'https://www.researchgate.net/profile/Kirstine_Manger',
'https://www.researchgate.net/profile/Kristina_Patmore',
'https://www.researchgate.net/profile/Laura_Jennings2',
'https://www.researchgate.net/profile/Laura_Kelly12',
'https://www.researchgate.net/profile/Laura_Pearce',
'https://www.researchgate.net/profile/Laura_Rozario',
'https://www.researchgate.net/profile/Laura_Suz',
'https://www.researchgate.net/profile/Lesley_Walsingham',
'https://www.researchgate.net/profile/Li_Chen232',
'https://www.researchgate.net/profile/Linah_Rabarivola',
'https://www.researchgate.net/profile/Lizzie_Roeble2',
'https://www.researchgate.net/profile/Louise_Colville',
'https://www.researchgate.net/profile/Luca_Pegoraro2',
'https://www.researchgate.net/profile/Lucy_Dablin',
'https://www.researchgate.net/profile/Lydia_White2',
'https://www.researchgate.net/profile/Lynda_Murray4',
'https://www.researchgate.net/profile/Madeleine_Lewis',
'https://www.researchgate.net/profile/Magie_Williams',
'https://www.researchgate.net/profile/Maite_Guignard2',
'https://www.researchgate.net/profile/Mamy_Rajaonah',
'https://www.researchgate.net/profile/Marcella_Corcoran',
'https://www.researchgate.net/profile/Maria_Alvarez-Aguirre',
'https://www.researchgate.net/profile/Maria_Vorontsova',
'https://www.researchgate.net/profile/Marie_Briggs',
'https://www.researchgate.net/profile/Marie_Christine_Henniges',
'https://www.researchgate.net/profile/Marie_Helene_Weech',
'https://www.researchgate.net/profile/Mariko_Parslow',
'https://www.researchgate.net/profile/Mark_Lee47',
'https://www.researchgate.net/profile/Mark_Nesbitt',
'https://www.researchgate.net/profile/Martin_Baruffol',
'https://www.researchgate.net/profile/Martin_Cheek',
'https://www.researchgate.net/profile/Martin_Deasy',
'https://www.researchgate.net/profile/Martin_Hamilton2',
'https://www.researchgate.net/profile/Martin_Staniforth',
'https://www.researchgate.net/profile/Martin_Xanthos',
'https://www.researchgate.net/profile/Matthew_Biggs3',
'https://www.researchgate.net/profile/Matthew_Blissett',
'https://www.researchgate.net/profile/Mauricio_Diazgranados',
'https://www.researchgate.net/profile/Melanie-Jayne_Howes2',
'https://www.researchgate.net/profile/Michael_Fay4',
'https://www.researchgate.net/profile/Michael_Frohlich',
'https://www.researchgate.net/profile/Michael_Gilbert11',
'https://www.researchgate.net/profile/Michael_Leach9',
'https://www.researchgate.net/profile/Michael_Van_Slageren',
'https://www.researchgate.net/profile/Michael_Way3',
'https://www.researchgate.net/profile/Michal_Zweig2',
'https://www.researchgate.net/profile/Michele_Sanchez',
'https://www.researchgate.net/profile/Mk_Langat2',
'https://www.researchgate.net/profile/Moctar_Sacande',
'https://www.researchgate.net/profile/Mohammed_Ayesh',
'https://www.researchgate.net/profile/Monika_Shaffer-Fehre',
'https://www.researchgate.net/profile/Monique_Simmonds',
'https://www.researchgate.net/profile/Morvah_George',
'https://www.researchgate.net/profile/Natasha_Ali',
'https://www.researchgate.net/profile/Nicholas_Black3',
'https://www.researchgate.net/profile/Nicholas_Sadgrove',
'https://www.researchgate.net/profile/Nicola_Biggs',
'https://www.researchgate.net/profile/Nina_Davies3',
'https://www.researchgate.net/profile/Niroshini_Epitawalage',
'https://www.researchgate.net/profile/Noeleen_Smyth2',
'https://www.researchgate.net/profile/Oliver_Ellingham',
'https://www.researchgate.net/profile/Oliver_Hooper2',
'https://www.researchgate.net/profile/Oliver_Whaley',
'https://www.researchgate.net/profile/Olivier_Maurin',
'https://www.researchgate.net/profile/Olwen_Grace',
'https://www.researchgate.net/profile/Oscar_Perez-Escobar',
'https://www.researchgate.net/profile/P_Brandham',
'https://www.researchgate.net/profile/Pablo_Gomez_Barreiro',
'https://www.researchgate.net/profile/Panagiota_Penny_Malakasi',
'https://www.researchgate.net/profile/Paolo_Ceci',
'https://www.researchgate.net/profile/Paul_Cannon5',
'https://www.researchgate.net/profile/Paul_Kirk5',
'https://www.researchgate.net/profile/Paul_Smith44',
'https://www.researchgate.net/profile/Paul_Wilkin',
'https://www.researchgate.net/profile/Paula_Rudall',
'https://www.researchgate.net/profile/Pepijn_Kooij',
'https://www.researchgate.net/profile/Peter_Gasson',
'https://www.researchgate.net/profile/Peter_Roberts18',
'https://www.researchgate.net/profile/Peter_Toorop',
'https://www.researchgate.net/profile/Philip_Seaton',
'https://www.researchgate.net/profile/Philippa_Ryan2',
'https://www.researchgate.net/profile/Rachael_Davies2',
'https://www.researchgate.net/profile/Rafael_Govaerts2',
'https://www.researchgate.net/profile/Rahim_Dina',
'https://www.researchgate.net/profile/Raquel_Negrao',
'https://www.researchgate.net/profile/Raquel_Pino-Bodas',
'https://www.researchgate.net/profile/Raymond_Harley',
'https://www.researchgate.net/profile/Renata_Borosova',
'https://www.researchgate.net/profile/Renee_Grayer',
'https://www.researchgate.net/profile/Rhian_Smith',
'https://www.researchgate.net/profile/Rich_Wright',
'https://www.researchgate.net/profile/Richard_Bateman3',
'https://www.researchgate.net/profile/Richard_Dee',
'https://www.researchgate.net/profile/Robert_Allkin',
'https://www.researchgate.net/profile/Robert_OSullivan2',
'https://www.researchgate.net/profile/Roberta_Gargiulo',
'https://www.researchgate.net/profile/Robin_Probert',
'https://www.researchgate.net/profile/Robyn_Cowan',
'https://www.researchgate.net/profile/Robyn_Powell2',
'https://www.researchgate.net/profile/Roseina_Woods',
'https://www.researchgate.net/profile/Rosemary_Newton',
'https://www.researchgate.net/profile/Rowan_Schley',
'https://www.researchgate.net/profile/Rowena_Hill3',
'https://www.researchgate.net/profile/Rui_Fang',
'https://www.researchgate.net/profile/Rui_Fang6',
'https://www.researchgate.net/profile/Ruth_Clark3',
'https://www.researchgate.net/profile/Ruth_Eastwood',
'https://www.researchgate.net/profile/Ruth_Harker',
'https://www.researchgate.net/profile/Sahr_Mian',
'https://www.researchgate.net/profile/Samuel_Pironon',
'https://www.researchgate.net/profile/Sara_Barrios',
'https://www.researchgate.net/profile/Sara_Edwards3',
'https://www.researchgate.net/profile/Sara_Gomez-Cabellos',
'https://www.researchgate.net/profile/Sarah_Morris5',
'https://www.researchgate.net/profile/Serene_Hargreaves',
'https://www.researchgate.net/profile/Shahina_Ghazanfar',
'https://www.researchgate.net/profile/Sharon_Balding',
'https://www.researchgate.net/profile/Si_Chong_Chen',
'https://www.researchgate.net/profile/Sidonie_Bellot',
'https://www.researchgate.net/profile/Simon_Mayo',
'https://www.researchgate.net/profile/Simon_Thundow',
'https://www.researchgate.net/profile/Solofo_Rakotoarisoa',
'https://www.researchgate.net/profile/Sonia_Dhanda2',
'https://www.researchgate.net/profile/Steven_Bachman',
'https://www.researchgate.net/profile/Sue_Frisby',
'https://www.researchgate.net/profile/Susana_Baena',
'https://www.researchgate.net/profile/Sven_Buerki',
'https://www.researchgate.net/profile/Sylvia_Phillips',
'https://www.researchgate.net/profile/Terence_Pennington',
'https://www.researchgate.net/profile/Thaise_Emilio',
'https://www.researchgate.net/profile/Theo_Llewellyn',
'https://www.researchgate.net/profile/Theo_Llewellyn2',
'https://www.researchgate.net/profile/Thomas_Heller7',
'https://www.researchgate.net/profile/Thomas_Prescott',
'https://www.researchgate.net/profile/Tim_Fulcher2',
'https://www.researchgate.net/profile/Tim_Pearce4',
'https://www.researchgate.net/profile/Tim_Wilkinson8',
'https://www.researchgate.net/profile/Timothy_Coker',
'https://www.researchgate.net/profile/Timothy_Harris2',
'https://www.researchgate.net/profile/Timothy_Marks',
'https://www.researchgate.net/profile/Timothy_Utteridge',
'https://www.researchgate.net/profile/Tiziana_Ulian',
'https://www.researchgate.net/profile/Tom_Reynolds2',
'https://www.researchgate.net/profile/Tuula_Niskanen',
'https://www.researchgate.net/profile/Udayangani_Liu',
'https://www.researchgate.net/profile/Umair_Sarwar2',
'https://www.researchgate.net/profile/Viswambharan_Sarasan',
'https://www.researchgate.net/profile/William_Baker',
'https://www.researchgate.net/profile/William_Milliken3',
'https://www.researchgate.net/profile/Xander_Burgt',
'https://www.researchgate.net/profile/Yan_Ng4',
'https://www.researchgate.net/profile/Yannick_Woudstra',
'https://www.researchgate.net/profile/Zhi_Qiang_Shee',
'https://www.researchgate.net/profile/Zoe_Goodwin4',
);

$urls=array(
//'https://www.researchgate.net/profile/Michael_Barfuss',
//'https://www.researchgate.net/scientific-contributions/36178342_Stephan_W_Gale',
//'https://www.researchgate.net/profile/Ching_Long_Yeh',

//'https://www.researchgate.net/profile/Antonio_Brescovit',

'https://www.researchgate.net/profile/Martin_Ramirez6',
'https://www.researchgate.net/profile/Santiago_Aisen',
'https://www.researchgate.net/profile/Galina_Azarkina',
'https://www.researchgate.net/profile/Yuri_Marusik',

'https://www.researchgate.net/profile/Alireza_Zamani4',
'https://www.researchgate.net/profile/Mikhail_Omelko',
'https://www.researchgate.net/profile/Sergei_Zonstein',
'https://www.researchgate.net/profile/Anna_Sestakova',
'https://www.researchgate.net/profile/Alexander_Fomichev',
'https://www.researchgate.net/profile/Tatyana_Tuneva',


'https://www.researchgate.net/profile/Aaron_Smith40',
'https://www.researchgate.net/profile/Abel_Perez_Gonzalez',
'https://www.researchgate.net/profile/Adriana_Ruggiero2',
'https://www.researchgate.net/profile/Alain_Dubois',
'https://www.researchgate.net/profile/Alexander_Gromov',
'https://www.researchgate.net/profile/Alexandra_Ravelo',
'https://www.researchgate.net/profile/Alexandre_Bonaldo',
'https://www.researchgate.net/profile/Alvaro_Laborda',
'https://www.researchgate.net/profile/Andres_Ojanguren',
'https://www.researchgate.net/profile/Anna_Christin_Joel',
'https://www.researchgate.net/profile/Anne_Thessen',
'https://www.researchgate.net/profile/Barry_Smith4',
'https://www.researchgate.net/profile/Bernhard_Huber',
'https://www.researchgate.net/profile/Bob_Kallal',
'https://www.researchgate.net/profile/Brent_Opell',
'https://www.researchgate.net/profile/Camilo_Mattoni',
'https://www.researchgate.net/profile/Candice_Owen2',
'https://www.researchgate.net/profile/Caroline_Grannemann',
'https://www.researchgate.net/profile/Charles_Griswold',
'https://www.researchgate.net/profile/Charles_Haddad',
'https://www.researchgate.net/profile/Christian_Wirkner',
'https://www.researchgate.net/profile/Christopher_Mungall',
'https://www.researchgate.net/profile/Claudia_Szumik',
'https://www.researchgate.net/profile/Cor_Vink',
'https://www.researchgate.net/profile/Cristian_Grismado',
'https://www.researchgate.net/profile/Cristina_Scioscia',
'https://www.researchgate.net/profile/Dakota_Piorkowski',
'https://www.researchgate.net/profile/Dante_Poy',
'https://www.researchgate.net/profile/Darrell_Ubick',
'https://www.researchgate.net/profile/David_Penney',
'https://www.researchgate.net/profile/Diogo_Castro7',
'https://www.researchgate.net/profile/Eduardo_Soto5',
'https://www.researchgate.net/profile/Eliecer_Gutierrez',
'https://www.researchgate.net/profile/Eva_Huala',
'https://www.researchgate.net/profile/Facundo_Labarque',
'https://www.researchgate.net/profile/Fadia_Ceccarelli',
'https://www.researchgate.net/profile/Felipe_Rego',
'https://www.researchgate.net/profile/Gavin_Zhang_zhangguanyang',
'https://www.researchgate.net/profile/George_Zug',
'https://www.researchgate.net/profile/Gilbert_Barrantes',
'https://www.researchgate.net/profile/Gonzalo_D_Rubio',
'https://www.researchgate.net/profile/Guilherme_Azevedo',
'https://www.researchgate.net/profile/Guillermo_Martinez_Pastur',
'https://www.researchgate.net/profile/Gustavo_Hormiga',
'https://www.researchgate.net/profile/Gustavo_Paterno2',
'https://www.researchgate.net/profile/Gustavo_Sebastian_Cabanne2',
'https://www.researchgate.net/profile/Hong_Cui10',
'https://www.researchgate.net/profile/Hong_Zhang_Zhou',
'https://www.researchgate.net/profile/Ignacio_Escapa',
'https://www.researchgate.net/profile/Ignacio_Soto2',
'https://www.researchgate.net/profile/Ivan_Magalhaes',
'https://www.researchgate.net/profile/Jaime_Pizarro-Araya',
'https://www.researchgate.net/profile/James_Balhoff',
'https://www.researchgate.net/profile/Jan_Bosselaers',
'https://www.researchgate.net/profile/Jason_Bond3',
'https://www.researchgate.net/profile/Jeremy_Miller2',
'https://www.researchgate.net/profile/Jonas_Wolff',
'https://www.researchgate.net/profile/Jonathan_Coddington',
'https://www.researchgate.net/profile/Jonathan_Liria',
'https://www.researchgate.net/profile/Jose_Ochoa5',
'https://www.researchgate.net/profile/Kamaljit_Bawa',
'https://www.researchgate.net/profile/Lara_Lopardo',
'https://www.researchgate.net/profile/Lars_Vogt',
'https://www.researchgate.net/profile/Laura_Juarez2',
'https://www.researchgate.net/profile/Laurel_Cooper',
'https://www.researchgate.net/profile/Liliana_Mola',
'https://www.researchgate.net/profile/Lorenzo_Prendini',
'https://www.researchgate.net/profile/Louise_Crowley2',
'https://www.researchgate.net/profile/Luis_Ceriaco',
'https://www.researchgate.net/profile/Luis_Pereira15',
'https://www.researchgate.net/profile/Luis_Piacentini',
'https://www.researchgate.net/profile/Marcos_Ercoli2',
'https://www.researchgate.net/profile/Margret_Weissbach',
'https://www.researchgate.net/profile/Maria_Lencinas',
'https://www.researchgate.net/profile/Mariana_Barone',
'https://www.researchgate.net/profile/Martin_Ramirez6',
'https://www.researchgate.net/profile/Matias_Izquierdo2',
'https://www.researchgate.net/profile/Miquel_Arnedo',
'https://www.researchgate.net/profile/Nico_Franz',
'https://www.researchgate.net/profile/Nicolas_Mongiardino_Koch',
'https://www.researchgate.net/profile/Paula_Mabee',
'https://www.researchgate.net/profile/Peter_Michalik',
'https://www.researchgate.net/profile/Pier_Luigi_Buttigieg',
'https://www.researchgate.net/profile/Pio_Colmenares',
'https://www.researchgate.net/profile/Regiane_Saturnino',
'https://www.researchgate.net/profile/Renner_Baptista2',
'https://www.researchgate.net/profile/Renzo_Adilardi',
'https://www.researchgate.net/profile/Rosina_Soler',
'https://www.researchgate.net/profile/Santiago_Aisen',
'https://www.researchgate.net/profile/Shahan_Derkarabetian',
'https://www.researchgate.net/profile/Sofia_Martinez',
'https://www.researchgate.net/profile/Steven_Chong3',
'https://www.researchgate.net/profile/Suresh_Benjamin',
'https://www.researchgate.net/profile/Suzanna_Lewis',
'https://www.researchgate.net/profile/Szuts_Tamas',
'https://www.researchgate.net/profile/Tim_Dederichs',
'https://www.researchgate.net/profile/Todd_Blackledge',
'https://www.researchgate.net/profile/Veronica_Pereyra',
'https://www.researchgate.net/profile/Victoria_Werenkraut',
'https://www.researchgate.net/profile/Wasila_Dahdul',
'https://www.researchgate.net/profile/Wc_Wheeler',

);

$urls = array(
//'https://www.researchgate.net/profile/Phetlasy_Souladeth2',
//'https://www.researchgate.net/profile/Son_Dang9',
//'https://www.researchgate.net/profile/Tetsukazu_Yahara',
//'https://www.researchgate.net/scientific-contributions/2066683599_Shuichiro_Tagane',
//'https://www.researchgate.net/profile/Viet_Nguyen91',
//'https://www.researchgate.net/profile/Ngoc_Nguyen52',
'https://www.researchgate.net/profile/Ai_Qun_Hu',
'https://www.researchgate.net/profile/Huaizhen_Tian',
'https://www.researchgate.net/profile/Cheng_Zhiquan2',
'https://www.researchgate.net/profile/Somran_Suddee',
'https://www.researchgate.net/profile/Akiko_Soejima',
'https://www.researchgate.net/profile/David_Middleton4',

/*
// not the zoologists, despite what ResearchGate says
'https://www.researchgate.net/profile/Yan_Fang32',
'https://www.researchgate.net/profile/Zhuqing_He',
*/

'https://www.researchgate.net/profile/Paolo_Rosa2',

'https://www.researchgate.net/profile/Orlando_Jara',

'https://www.researchgate.net/profile/Simon_Laegaard',
'https://www.researchgate.net/profile/Diego_Giraldo-Canas',
'https://www.researchgate.net/profile/Konstantin_Romaschenko',
'https://www.researchgate.net/profile/Nancy_Refulio_Rodriguez',

'https://www.researchgate.net/profile/Pablo_Munoz_Rodriguez',

'https://www.researchgate.net/profile/Yong_Kang_Sima',
'https://www.researchgate.net/profile/Yu_Shui',
'https://www.researchgate.net/profile/Yunhong_Tan',
'https://www.researchgate.net/profile/Ren_Li6',

'https://www.researchgate.net/profile/Vu_Nam4',
'https://www.researchgate.net/profile/Anton_Weber',

'https://www.researchgate.net/profile/Alan_Beu',

'https://www.researchgate.net/profile/Gustavo_Ruiz9',
'https://www.researchgate.net/profile/Roberta_Valente',


);

$urls=array(
'https://www.researchgate.net/profile/Keita_Kuroda',
//'https://www.researchgate.net/profile/Artur_Taszakowski',
//'https://www.researchgate.net/profile/Jacek_Gorczyca',
//'https://www.researchgate.net/profile/Aleksander_Herczek',
);




// from file
if (0)
{
	$urls = array();
	$filename = 'urls.txt';
	
	$file_handle = fopen($filename, "r");
	while (!feof($file_handle)) 
	{
		$urls[] = trim(fgets($file_handle));
	}
}
	


//----------------------------------------------------------------------------------------
// Add items to the queue

$force = false;
$force = true;


foreach ($urls as $url)
{
	echo $url . "\n";
	enqueue($url, $force);
}
	
//----------------------------------------------------------------------------------------
// Resolve items

// Do this twice, the first time dequeue items in our queue, as we do so we
// build a list of things linked to those items. We store those and can then enqueue them,
// but this time ignoring the links. This enables us to crawl the web of objects one level deep,
// adding records but not ending up crawling the whole web!

// Array to hold links we discover
$links = array();

while (!queue_is_empty())
{	
	$result = dequeue(100);
	
	$links = array_merge($links, $result);
}

// links we have found
//print_r($links);

// For each additional link add it to the queue if we haven't already found it

foreach ($links as $url)
{
	echo $url . "\n";
	enqueue($url, false);
}

// Empty queue, ignoring any further links
while (!queue_is_empty())
{	
	dequeue(100);
}


?>